# Generated by Django 5.0 on 2024-02-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseactivity',
            old_name='course_activity_type',
            new_name='activity_type',
        ),
    ]
