# Generated by Django 5.0.1 on 2024-02-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0002_rename_course_activity_type_courseactivity_activity_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetag',
            unique_together={('course', 'tag')},
        ),
    ]
