# Generated by Django 5.0.1 on 2024-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0003_alter_coursetag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Complete', 'Complete'), ('Blocked', 'Blocked')], default='Active', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together={('course', 'student')},
        ),
    ]
