# Generated by Django 5.0.1 on 2024-02-18 19:11

import django.db.models.deletion
import elearning_base.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0004_enrollments_status_alter_enrollments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to=elearning_base.models.course_img_directory_path),
        ),
        migrations.AlterField(
            model_name='courseactivitymaterial',
            name='file',
            field=models.FileField(blank=True, upload_to=elearning_base.models.activity_material_file_directory_path),
        ),
        migrations.AlterField(
            model_name='courseactivitymaterial',
            name='image',
            field=models.ImageField(blank=True, upload_to=elearning_base.models.activity_material_image_directory_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=elearning_base.models.submission_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=elearning_base.models.user_img_directory_path),
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
