# Generated by Django 5.0.1 on 2024-02-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0005_alter_course_course_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='updated_at',
        ),
    ]
