# Generated by Django 5.0.1 on 2024-02-29 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_base', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
